### ISSUE TITLE
Agent resolves webdomain DNS name into IPv6 that is unreachable

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/sdn-sense.github.io#2]
@juztas 

In the docker-agent container, with main.conf config `webdomain = https://sense-dtn.fnal.gov:8443`, the URL will resolve into IPv6 address, which is often not routable. 

My temporary solution is to add a manual IPv4 resolution to /etc/hosts, like
`131.225.2.40	sense-dtn.fnal.gov`

We could either disable IPv6 for the container or always add this /etc/hosts entry (through ./fresh-siterm-agent-install.sh or through run-wrapper.sh)

**Comment by juztas** [comment]
In this case, there should be no IPv6 DNS Entry for that end host - seems the best solution (Why not fixing root issue?).  If this is not the way to go - then this is a single end-host issue. If other sites show that IPv6 is a big issue for them ( Would be weird) then we can enforce it to listen only on IPv4.
